include: package:effective_dart/analysis_options.1.3.0.yaml


# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

linter:
   rules:
      prefer_expression_function_bodies
      prefer_typing_uninitialized_variables
      use_function_type_syntax_for_parameters
      
analyzer:
   exclude:
    
