name: dart_lab
description: Dart code lab that is part of the probable notes
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/rayk/probableNotes

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  path: ^1.7.0
  numeral: ^1.0.4

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
